demo/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from demo.views import *

urlpatterns = [
    path('', catalog, name='catalog'),
    path('product/<pk>', product, name='product'),
    path('cart/', cart, name='cart'),
    path('add_cart/', add_cart, name='add_cart'),
    path('dif_cart/', dif_cart, name='dif_cart'),
    path('create_order/', create_order, name='create_order'),
    path('orders/', orders, name='orders'),
    path('delete_order/<pk>', delete_order, name='delete_order'),

    path('contact/', contact_company, name='contact'),
    path('about/', about, name='about'),

    path('login/', LoginView.as_view(), name='login'),
    path('register/', RegisterUserView.as_view(), name='register'),
    path('validate_login/', check_login, name='valid_login'),
    path('validate_email/', check_email, name='valid_email'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

demoproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from demo import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(urls)),
]

urlpatterns += static(settings.STATIC_URL)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

demo/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.crypto import get_random_string


def get_name_img(instance, filename):
    return '_'.join([get_random_string(length=5), filename])


class User(AbstractUser):
    username = models.CharField(blank=False, unique=True, max_length=254)
    email = models.CharField(blank=False, unique=True, max_length=254)
    password = models.CharField(blank=False, max_length=254)

    name = models.CharField(blank=False, max_length=254)
    surname = models.CharField(blank=False, max_length=254)
    patronymic = models.CharField(blank=True, max_length=254)

    role = models.CharField(blank=False, choices=(('admin', 'администратор'), ('user', 'пользователь')), default='user',
                            max_length=254)

    def __str__(self):
        return ' '.join([self.name, self.username, self.surname])


class Product(models.Model):
    name = models.CharField(blank=False, max_length=254, verbose_name='Наименование')
    country = models.CharField(blank=False, max_length=254, verbose_name='Страна производитель')
    photo_file = models.ImageField(blank=False, verbose_name='Изображение товара', upload_to=get_name_img,
                                   max_length=254)
    price = models.DecimalField(blank=False, default=0.00, max_digits=9, decimal_places=2, verbose_name='Стоимость')
    count = models.IntegerField(blank=False, default=1, verbose_name='Количество на складе')
    year = models.IntegerField(blank=False, default=2022, verbose_name='Год производства')
    date = models.DateField(blank=False, auto_now_add=True, verbose_name='Дата поступления на склад')
    category = models.ForeignKey('Category', on_delete=models.CASCADE, verbose_name='Категория товара')

    def __str__(self):
        return ' '.join([self.name, str(self.price)])


class Category(models.Model):
    name = models.CharField(blank=False, max_length=254, verbose_name='Название категории')

    def __str__(self):
        return self.name


class Cart(models.Model):
    user = models.ForeignKey('User', on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    count = models.IntegerField(blank=False, default=1)

    def __str__(self):
        return ' '.join([str(self.product), str(self.count)])


class OrderInItem(models.Model):
    order = models.ForeignKey('Order', on_delete=models.CASCADE, verbose_name='Заказ')
    product = models.ForeignKey('Product', on_delete=models.CASCADE, verbose_name='Продукт')
    count = models.IntegerField(blank=False, default=1, verbose_name='Количество')
    price = models.DecimalField(blank=False, default=0.00, max_digits=9, decimal_places=2, verbose_name='Стоимость')


class Order(models.Model):
    STATUS_CHOICE = (('confirm', 'подтверждённый'), ('new', 'новый'), ('canceled', 'отменённый'))
    date = models.DateTimeField(auto_now_add=True, blank=False, verbose_name='Дата создания заказа')
    user = models.ForeignKey('User', on_delete=models.CASCADE, verbose_name='Пользователь')
    reject_reason = models.TextField(blank=True, verbose_name='Причина отказа')
    status = models.CharField(blank=False,
                              choices=STATUS_CHOICE,
                              default='new',
                              max_length=254)
    product = models.ManyToManyField(Product, related_name='orders', through=OrderInItem)

    def count_product(self):
        counter = 0
        itemInOrder = OrderInItem.objects.filter(order_id=self.id).all()

        for item in itemInOrder:
            counter += item.count

    def status_verbose(self):
        return dict(self.STATUS_CHOICE)[self.status]

    def __str__(self):
        return str(self.date)

demo/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator

from demo.models import User


def lenght_password(password):
    if len(password) < 6:
        raise ValidationError('Длина пароля должна быть неменьше шести символов')


class RegisterUserForm(forms.ModelForm):
    name = forms.CharField(label='Имя', error_messages={
        'required': 'Данное поле обязательно'
    }, required=True, validators=[RegexValidator("^[а-яА-Я- ]+$", message='Допустима только латиница и пробел')],
                           widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'имя'}))

    surname = forms.CharField(label='Фамилия', error_messages={
        'required': 'Данное поле обязательно'
    }, required=True, validators=[RegexValidator("^[а-яА-Я- ]+$", message='Допустима только латиница и пробел')],
                              widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'фамилия'}))

    patronymic = forms.CharField(label='Отчество', required=False, validators=[
        RegexValidator("^[а-яА-Я- ]+$", message='Допустима только латиница и пробел')],
                                 widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'отчество'}))

    username = forms.CharField(label='Логин', error_messages={
        'required': 'Данное поле обязательно',
        'unique': 'Данное поле не уникально'
    }, required=True, validators=[
        RegexValidator("^[a-zA-Z0-9-_]+$", message="Разрешены латиница, цифры и знак нижнего подчёркивания")],
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'логин'}))

    email = forms.CharField(label='Почта', error_messages={
        'required': 'Данное поле обязательно',
        'unique': 'Данное поле не уникально'
    }, required=True, widget=forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'почта'}))

    password1 = forms.CharField(label='Пароль', error_messages={
        'required': 'Данное поле обязательно'
    }, required=True, validators=[lenght_password],
                                widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'пароль'}))

    password2 = forms.CharField(label='Повторите пароль', error_messages={
        'required': 'Данное поле обязательно'
    }, required=True, widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'ещё пароль'}))

    rules = forms.BooleanField(label='Пользовательское соглашение',
                               widget=forms.CheckboxInput(attrs={'class': 'form-control'}), initial=True,
                               error_messages={
                                   'required': 'Данное поле обязательно',
                               })

    def clean(self):
        super().clean()
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password2 and password1 and password1 != password2:
            raise ValidationError({
                'password2': ValidationError('Пароли не совподают')
            })

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data.get('password1'))

        if user:
            user.save()

        return user

    class Meta:
        model = User
        fields = ('name', 'surname', 'patronymic', 'username', 'email', 'password1', 'password2', 'rules')


class OrderAdminForm(forms.ModelForm):
    def clean(self):
        super().clean()
        status = self.cleaned_data.get('status')
        reject_reason = self.cleaned_data.get('reject_reason')

        if status == 'canceled' and not reject_reason:
            raise ValidationError({
                'reject_reason': "При отмене заказа нужно указать причину отмены"
            })

        if self.instance.status != 'new':
            raise ValidationError({
                'status': 'Статус можно менять только у новых заказов'
            })

demo/views.py
from django.core import validators
from django.core.exceptions import ValidationError
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView

from demo.forms import RegisterUserForm
from demo.models import Product, Category, Cart, User, Order, OrderInItem


class RegisterUserView(CreateView):
    template_name = 'registration/register.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('login')


def check_login(request):
    user = User.objects.filter(username=request.GET.get('login'))
    if user:
        return JsonResponse({
            'errors': 'Login not unique'
        })

    return JsonResponse({
        'success': 'Login success'
    })


def check_email(request):
    email = request.GET.get('email')

    try:
        validators.validate_email(email)
    except ValidationError as error:
        response = {
            'is_valid': False
        }
    else:
        response = {
            'is_valid': True,
            'is_taken': bool(User.objects.filter(email=email).first())
        }

    return JsonResponse(response)


def catalog(request):
    filter_product = request.GET.get('filter')
    if filter_product:
        products = Product.objects.filter(category__id=filter_product).all()
    else:
        products = Product.objects.all()

    order_by = request.GET.get('order_by')

    if order_by:
        products = products.order_by(order_by)
    else:
        products = products.order_by('-date')

    category = Category.objects.all()

    return render(request, 'demo/catalog.html', context={
        'products': products,
        'category': category,
    })


def product(request, pk):
    product = Product.objects.filter(id=pk).first()

    return render(request, 'demo/product.html', context={
        'product': product,
    })


def cart(request):
    carts = Cart.objects.filter(user=request.user).all()
    return render(request, 'demo/cart.html', context={'carts': carts})


def add_cart(request):
    product = Product.objects.filter(id=request.GET.get('product')).first()
    cart = Cart.objects.filter(user=request.user, product=product).first()

    if cart:
        if cart.count + 1 > product.count:
            return JsonResponse({
                'error': "Can't add more"
            })

        cart.count += 1
        cart.save()

        return JsonResponse({
            'count': cart.count
        })
    cart = Cart.objects.create(user=request.user, product=product, count=1)

    return JsonResponse({
        'count': cart.count
    })


def dif_cart(request):
    product = Product.objects.filter(id=request.GET.get('product')).first()
    cart = Cart.objects.filter(user=request.user, product=product).first()

    if cart:
        if cart.count - 1 <= 0:
            cart.delete()
            return JsonResponse({
                'error': "belove zero"
            })
        cart.count -= 1
        cart.save()

        return JsonResponse({
            'count': cart.count
        })

    return JsonResponse({
        'error': "Product not found"
    })


def create_order(request):
    check_password = request.user.check_password(request.GET.get('password'))

    if check_password:
        items_cart = Cart.objects.filter(user=request.user).all()

        if items_cart:
            order = Order.objects.create(user=request.user)

            print(order.status_verbose())

            for item in items_cart:
                item_in_order = OrderInItem.objects.create(order=order, product=item.product, count=item.count,
                                                           price=item.product.price * item.count)
                item.delete()

            return JsonResponse({
                'success': 'Order create'
            })
        else:
            return JsonResponse({
                'error': 'Void cart'
            })

    return JsonResponse({
        'invalid_password': 'invalid password'
    })


def orders(request):
    order = Order.objects.filter(user=request.user).all()
    return render(request, 'demo/order.html', context={'orders': order})


def delete_order(request, pk):
    order = Order.objects.filter(user=request.user, id=pk)
    if order:
        order.delete()

    return redirect(reverse_lazy('orders'))



def contact_company(request):
    return render(request, 'demo/contact.html')


def about(request):
    return render(request, 'demo/about.html', context={'products': Product.objects.order_by('-date')[:5]})

templates/demo/about.html
{% extends 'base.html' %}

{% block title %} Каталог {% endblock %}

{% block content %}
    <h1>О нас</h1>
    <p>
        Lorem ipsum
    </p>
    <div class="container" style="display: flex; justify-content: center">
        <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel" style="width: 700px">
            <ol class="carousel-indicators">
                {% for item in products %}
                    <li data-target="#carouselExampleCaptions" data-slide-to="{{ forloop.counter }}" class="{% if forloop.counter == 1 %} active {% endif %}"></li>
                {% endfor %}
            </ol>
            <div class="carousel-inner">
                {% for item in products %}
                    <div class="carousel-item {% if forloop.counter == 1 %} active {% endif %}">
                        <img src="{{ item.photo_file.url }}" class="d-block w-100" alt="{{ item.name }}" height="300px"
                             style="object-fit: contain">
                        <div class="carousel-caption d-none d-md-block" style="background-color: rgba(0, 0, 0, 0.5)">
                            <h5>{{ item.name }}</h5>
                            <p>{{ item.price }}руб | {{ item.year }}</p>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <button class="carousel-control-prev" type="button" data-target="#carouselExampleCaptions"
                    data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-target="#carouselExampleCaptions"
                    data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </button>
        </div>
    </div>


{% endblock %}

templates/demo/cart.html
{% extends 'base.html' %}

{% block title %} Корзина {% endblock %}

{% block content %}
    <h1>Корзина</h1>
    <div class="carts">
        {% for item in carts %}
            <div class="card" style="width: 300px;">
                <img src="{{ item.product.photo_file.url }}" class="card-img-top" alt="{{ item.product.name }}">
                <div class="card-body">
                    <h5 class="card-title">{{ item.product.name }}</h5>
                    <li class="list-group-item">Цена товара: {{ item.product.price }}</li>
                    </ul>
                </div>
                <div class="card-body">
                    <p class="card-text">В корзине: <span class="num">{{ item.count }}</span></p>
                    <a href="{% url 'product' item.pk %}" class="card-link">Подробнее</a> <br>

                    <input type="button" value="+" class="btn btn-light"
                           onclick="addToCart(this, {{ item.product.pk }})">
                    <input type="button" value="-" class="btn btn-light"
                           onclick="difToCart(this, {{ item.product.pk }})">

                </div>
                <div class="card-footer mes-hide">
                    1
                </div>
            </div>
        {% endfor %}
    </div>
    {% if carts %}
        <div class="form">
            <div class="form-group">
                <label for="user-password">Пароль</label>
                <input type="password" name="user_password" id="user-password" placeholder="super-secret"
                       class="form-control">
            </div>
            <input type="button" name="user_password" value="оформить заказ" class="btn btn-primary"
                   onclick="checkout(this, {% url 'orders' %})">
            <span class="mes mes-hide">1</span>
        </div>
    {% endif %}

    <script>
        addToCart = async (target, pk) => {
            const res = await fetch(`/add_cart/?product=${pk}`).then(res => res.json());
            let footer = target.parentElement.parentElement.querySelector('.card-footer');

            footer.classList.remove('mes-success');
            footer.classList.remove('mes-error');
            footer.innerHTML = '';

            if (res.error) {
                footer.innerHTML = 'Товар не добавлен в корзину';
                footer.classList.add('mes-error');
            } else {
                footer.innerHTML = 'Товар добавлен в корзину';
                footer.classList.add('mes-success');
                target.parentElement.querySelector('.num').innerHTML = res.count;
            }

            setTimeout(() => {
                footer.classList.remove('mes-success');
                footer.classList.remove('mes-error');
            }, 1000)
        }

        difToCart = async (target, pk) => {
            const res = await fetch(`/dif_cart/?product=${pk}`).then(res => res.json());
            let footer = target.parentElement.parentElement.querySelector('.card-footer');

            footer.classList.remove('mes-success');
            footer.classList.remove('mes-error');
            footer.innerHTML = '';

            if (res.error) {
                target.parentElement.parentElement.remove()
            } else {
                footer.innerHTML = 'Товар убран из корзины';
                footer.classList.add('mes-success');
                target.parentElement.querySelector('.num').innerHTML = res.count;
            }

            setTimeout(() => {
                footer.classList.remove('mes-success');
                footer.classList.remove('mes-error');
            }, 1000)
        }

        checkout = async (target, successUrl) => {
            let password = document.getElementById('user-password').value;
            const res = await fetch(`/create_order/?password=${password}`).then(res => res.json());

            let mes = target.parentElement.querySelector('.mes');
            mes.innerHTML = '';
            mes.classList.remove('mes-success');
            mes.classList.remove('mes-error');
            mes.classList.remove('mes-hide');

            if (res.invalid_password) {
                mes.innerHTML = 'Неверный пароль';
                mes.classList.add('mes-error');
            }

            if (res.success){
                mes.innerHTML = 'Заказ успешно создан';
                mes.classList.add('mes-success');
                document.querySelectorAll('.card').forEach((item, i, arr)=>{
                    item.remove();
                });
                setTimeout(()=>{
                    location.href = successUrl;
                }, 1000);
            }

            setTimeout(() => {
                mes.classList.remove('mes-success');
                mes.classList.remove('mes-error');
                mes.classList.add('mes-hide');
                mes.innerHTML = '';
            }, 1000)
        }
    </script>

{% endblock %}

templates/demo/catalog.html
{% extends 'base.html' %}

{% block title %} Каталог {% endblock %}

{% block content %}
    <h1>Каталог</h1>

    <div class="sort">
        <table>
            <tr>
                <td><span>Сортировать по</span></td>
                <td class="btn-group" role="group" aria-label="Basic example">

                    <a href="{% url 'catalog' %}?filter={{ request.GET.filter }}&order_by=year" type="button"
                       class="btn {% if request.GET.order_by == 'year' %} btn-primary {% else %} btn-secondary {% endif %}">дате</a>
                    <a href="{% url 'catalog' %}?filter={{ request.GET.filter }}&order_by=name" type="button"
                       class="btn {% if request.GET.order_by == 'name' %} btn-primary {% else %} btn-secondary {% endif %}">названию</a>
                    <a href="{% url 'catalog' %}?filter={{ request.GET.filter }}&order_by=price" type="button"
                       class="btn {% if request.GET.order_by == 'price' %} btn-primary {% else %} btn-secondary {% endif %}">цене</a>
                </td>
                <td>
                    {% if request.GET.order_by %}
                        <a href="{% url 'catalog' %}?filter={{ request.GET.filter }}">Сбросить</a>
                    {% endif %}
                </td>
            </tr>
            <tr>
                <td><span>Фильтры по категориям</span></td>
                <td class="btn-group" role="group" aria-label="Basic example">
                    {% for item in category %}
                        <a href="{% url 'catalog' %}?filter={{ item.pk }}&order_by={{ request.GET.order_by }}"
                           class="btn {% if request.GET.filter == item.pk|stringformat:'s' %} btn-primary {% else %} btn-secondary {% endif %}">{{ item.name }}</a>
                    {% endfor %}
                </td>
                <td>
                    {% if request.GET.filter %}
                        <a href="{% url 'catalog' %}?order_by={{ request.GET.order_by }}">Сбросить</a>
                    {% endif %}
                </td>
            </tr>
        </table>
    </div>



    <div class="catalog">
        {% for item in products %}
            <div class="card" style="width: 300px;">
                <img src="{{ item.photo_file.url }}" class="card-img-top" alt="{{ item.name }}">
                <div class="card-body">
                    <h5 class="card-title">{{ item.name }}</h5>
                    <p class="card-text">Lorem ipsum</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{ item.category.name }}</li>
                    <li class="list-group-item">{{ item.price }}руб</li>
                    <li class="list-group-item">{{ item.year }} год производства</li>
                    <li class="list-group-item">Производитель: {{ item.country }}</li>
                    <li class="list-group-item">На складе: {{ item.count }}</li>
                </ul>
                <div class="card-body">
                    <a href="{% url 'product' item.pk %}" class="card-link">Подробнее</a>

                    {% if user.is_authenticated %}
                        <span class="btn btn-primary" onclick="addToCart(this, {{ item.pk }})">В корзину</span>
                    {% endif %}
                </div>
                <div class="card-footer mes-hide">
                    1
                </div>
            </div>
        {% endfor %}
    </div>

    <script>
        addToCart = async (target, pk) => {
            const res = await fetch(`add_cart/?product=${pk}`).then(res => res.json());
            let footer = target.parentElement.parentElement.querySelector('.card-footer');

            footer.classList.remove('mes-success');
            footer.classList.remove('mes-error');
            footer.innerHTML = '';

            if (res.error) {
                footer.innerHTML = 'Товар не добавлен в корзину';
                footer.classList.add('mes-error');
            } else {
                footer.innerHTML = 'Товар добавлен в корзину';
                footer.classList.add('mes-success');
            }

            setTimeout(() => {
                footer.classList.remove('mes-success');
                footer.classList.remove('mes-error');
            }, 1000)
        }
    </script>


{% endblock %}

templates/demo/contact.html
{% extends 'base.html' %}

{% block title %} Каталог {% endblock %}

{% block content %}
    <h1>Контакты</h1>
    <ul>
        <li>
            Телефон: <a href="tel:3101010">310-10-10</a>
        </li>
        <li>
            Адрес: Улица пушкина дом колотушкино
        </li>
    </ul>
    <figure class="figure">
        {% load static %}
        <img src="{% static 'img/contact_map.webp' %}" class="figure-img img-fluid rounded" alt="Карта с местоположением" width="300px" height="300px">
        <figcaption class="figure-caption">Адрес: Улица пушкина дом колотушкино</figcaption>
    </figure>

{% endblock %}

templates/demo/order.html
{% extends 'base.html' %}

{% block title %} Заказы {% endblock %}

{% block content %}
    <h1>Заказы</h1>
    {% if orders %}
        <ul>
            {% for order in orders %}
                <li>
                    {{ order.date }} | {{ order.status_verbose }} |

                    <a href="{% url 'delete_order' order.pk %}" class="btn btn-danger">Удалить</a>
                    <ol>
                        {% if order.orderinitem_set %}
                            {% for item in order.orderinitem_set.all %}
                                <li>
                                    {{ item.product.name }} | {{ item.count }} | {{ item.price }}
                                </li>

                            {% endfor %}
                        {% endif %}
                    </ol>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <h2>Заказов нет</h2>
    {% endif %}

{% endblock %}

templates/demo/product.html
{% extends 'base.html' %}

{% block title %} Каталог {% endblock %}

{% block content %}
    <h1>Принтер {{ product.name }}</h1>
    <div style="display: flex; align-items: center">
        <ul>
            <li>
                Цена: {{ product.price }}руб
            </li>
            <li>
                Год произодства: {{ product.year }}
            </li>
            <li>
                Страна проихводитель: {{ product.country }}
            </li>
            <li>
                Количество на складе: {{ product.count }} штук
            </li>
        </ul>
        <img src="{{ product.photo_file.url }}" alt="{{ product.name }}">
    </div>

{% endblock %}